### ISSUE TITLE
Between 15 and 16 the 'u' was removed from the url

### ISSUE THREAD

**Issue by johanjanssen** [johanjanssen/TemurinChocolateyPackages#18]
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x86-32_windows_hotspot_15.0.2_7.msi

https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16%2B36/OpenJDK16-jdk_x86-32_windows_hotspot_16_36.msi

if ($url32 -match "${number}U") { $url32 = $url32 } else { $url32 = $null }
vs
if ($url32 -match "${number}") { $url32 = $url32 } else { $url32 = $null }

**Comment by RedBaron2** [comment]
@johanjanssen 
Why is the change to line 62 necessary?
This doesn't affect anything.

The change of not having the "U" next to the number in the URL shouldn't be even needed.

The only change needed was maybe the removal of the 14, 15 from the GetLatest function but even this is superficial.

I'll double check next week, and get back to this issue.

**Comment by johanjanssen** [comment]
@RedBaron2 good one, it indeed wasn't necessary. I just occasionally clean up the set so it only contains versions I actually want to build. Same goes for the versions in GetLatest, there it also prevents the application from checking if those versions got updates, so it speeds up the process a little bit.

**Comment by johanjanssen** [comment]
Fixed by:
https://github.com/johanjanssen/TemurinChocolateyPackages/commit/482016a18687616e27a9f9edf97c72868854c1bf
https://github.com/johanjanssen/TemurinChocolateyPackages/commit/09e7e28c2a209aa427d8b307044b45b0dbac011a
