### ISSUE TITLE
Packages installed in wrong directory

### ISSUE THREAD

**Issue by naliferopoulos** [johanjanssen/TemurinChocolateyPackages#29]
I have noticed that the Temurin11 package is now installed in a different directory than the expected. By skimming through the install helper I expected the installation directory to be the following (for x64):

C:\Program FIles\Temurin

Instead packages are installed to:

C:\Program Files\Eclipse Adoptium

The latter is mentioned as default in the Eclipse Adoptium MSI installer [documentation](https://adoptium.net/installation/windows/).
I also seem to recall this to have been caused by a recent upgrade of Temurin11. Could it perhaps be related to changes on the MSI installer behavior?

**Comment by johanjanssen** [comment]
Hi Nick,

Indeed, the default directory is set by the MSI installer. I think it was Temurin quite some time ago, but they already changed it more than a year ago. Also see https://github.com/johanjanssen/TemurinChocolateyPackages/issues/19 where we changed the documentation for the Chocolatey package.

If you look on https://community.chocolatey.org/packages/Temurin11 it mentions:
** Note: You must use INSTALLDIR with FeatureMain. INSTALLDIR Default is $env:Programfiles\Eclipse Adoptium **

So I don't think this is a bug? Maybe the install helper could be changed a bit to make it more clear, but I guess most people don't even look at the code :).

**Comment by naliferopoulos** [comment]
Oh sorry about that! I thought it was intended to be installed to Temurin, that's why I opened an issue! I somehow managed to miss that its documented! Thanks for your reply!

**Comment by johanjanssen** [comment]
No problem, I also had some problems with the different names (Temurin/Eclipse Adoptium) in the past, it's quite confusing :).
